coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
        informational: false

comment:
  layout: "reach,diff,files"
  behavior: default
