<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001140026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create stamp catalog tables (stamps, tags, places, join tables)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stamp_places (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name TEXT NOT NULL, url TEXT NOT NULL, catalog_key VARCHAR(64) NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STAMP_PLACE_CATALOG_KEY ON stamp_places (catalog_key)');
        $this->addSql('CREATE TABLE stamp_tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STAMP_TAG_NAME ON stamp_tags (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STAMP_TAG_SLUG ON stamp_tags (slug)');
        $this->addSql('CREATE TABLE stamps (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, name VARCHAR(255) NOT NULL, country VARCHAR(2) NOT NULL, type VARCHAR(16) NOT NULL, district VARCHAR(120) DEFAULT NULL, region VARCHAR(120) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STAMP_COUNTRY_TYPE_NUMBER ON stamps (country, type, number)');
        $this->addSql('CREATE TABLE stamp_stamp_tag (stamp_id INT NOT NULL, stamp_tag_id INT NOT NULL, PRIMARY KEY (stamp_id, stamp_tag_id))');
        $this->addSql('CREATE INDEX IDX_E7FC462FEF6E9F ON stamp_stamp_tag (stamp_id)');
        $this->addSql('CREATE INDEX IDX_E7FC462872E77DB ON stamp_stamp_tag (stamp_tag_id)');
        $this->addSql('CREATE TABLE stamp_stamp_place (stamp_id INT NOT NULL, stamp_place_id INT NOT NULL, PRIMARY KEY (stamp_id, stamp_place_id))');
        $this->addSql('CREATE INDEX IDX_FA74BC10FEF6E9F ON stamp_stamp_place (stamp_id)');
        $this->addSql('CREATE INDEX IDX_FA74BC102669745C ON stamp_stamp_place (stamp_place_id)');
        $this->addSql('ALTER TABLE stamp_stamp_tag ADD CONSTRAINT FK_E7FC462FEF6E9F FOREIGN KEY (stamp_id) REFERENCES stamps (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stamp_stamp_tag ADD CONSTRAINT FK_E7FC462872E77DB FOREIGN KEY (stamp_tag_id) REFERENCES stamp_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stamp_stamp_place ADD CONSTRAINT FK_FA74BC10FEF6E9F FOREIGN KEY (stamp_id) REFERENCES stamps (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stamp_stamp_place ADD CONSTRAINT FK_FA74BC102669745C FOREIGN KEY (stamp_place_id) REFERENCES stamp_places (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stamp_stamp_tag DROP CONSTRAINT FK_E7FC462FEF6E9F');
        $this->addSql('ALTER TABLE stamp_stamp_tag DROP CONSTRAINT FK_E7FC462872E77DB');
        $this->addSql('ALTER TABLE stamp_stamp_place DROP CONSTRAINT FK_FA74BC10FEF6E9F');
        $this->addSql('ALTER TABLE stamp_stamp_place DROP CONSTRAINT FK_FA74BC102669745C');
        $this->addSql('DROP TABLE stamp_places');
        $this->addSql('DROP TABLE stamp_tags');
        $this->addSql('DROP TABLE stamps');
        $this->addSql('DROP TABLE stamp_stamp_tag');
        $this->addSql('DROP TABLE stamp_stamp_place');
    }
}
